Adds tox/molecule test
wazo-platform/ansible-role-metadata pull request #2
Opened 2023-11-15 22:43 UTC by ahogui12

2023-11-20 19:43 UTC, sduthil requested changes, later dismissed

2023-11-20 19:43 UTC, sduthil commented on Jenkinsfile
> +        WAZO_MOLECULE_LOGS_DIR = "${WORKSPACE}/molecule/logs"
Is this variable really used?

2023-11-20 19:43 UTC, sduthil commented on molecule/default/molecule.yml
> +    ignore-certs: True
We should not ignore certificate errors when using Galaxy. Is this necessary?

2023-11-21 16:25 UTC, fblackburn1 commented
recheck

2023-11-21 16:28 UTC, fblackburn1 approved these changes

2023-11-21 16:30 UTC, fblackburn1 commented
regate

2023-11-21 16:32 UTC, merged